version: "3"
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: help_locally
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: